2021-01-09 09:06:06|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210109/06634983667962198.png
2021-01-09 10:50:05|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210109/06635046056481012.png
2021-01-09 11:08:03|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///avatar/20210109/06635056830475019.png
2021-01-09 13:57:19|DEBUG|succeed to upload file to UCloud_Engine_Local|https://www.qingwazb.com/upload///thumb/20210109/06635158399111890.png
2021-01-09 14:24:11|ERROR|User.UpdateFields|PDOException: Incorrect integer value: '' for column 'sex' at row 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(410): NotORM_Result->query('UPDATE cmf_user...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/User.php(72): NotORM_Result->update(Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/User.php(27): Model_User->userUpdate(42879, Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/User.php(1469): Domain_User->userUpdate(42879, Array)
#4 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_User->updateFields()
#5 /www/wwwroot/yunbao.com/public/appapi/index.php(15): PhalApi->response()
#6 {main}
2021-01-09 14:24:24|ERROR|User.UpdateFields|PDOException: Incorrect integer value: '' for column 'sex' at row 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(410): NotORM_Result->query('UPDATE cmf_user...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/User.php(72): NotORM_Result->update(Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/User.php(27): Model_User->userUpdate(42879, Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/User.php(1469): Domain_User->userUpdate(42879, Array)
#4 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_User->updateFields()
#5 /www/wwwroot/yunbao.com/public/appapi/index.php(15): PhalApi->response()
#6 {main}
2021-01-09 14:24:36|ERROR|User.UpdateFields|PDOException: Incorrect integer value: '' for column 'sex' at row 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(410): NotORM_Result->query('UPDATE cmf_user...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/User.php(72): NotORM_Result->update(Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/User.php(27): Model_User->userUpdate(42879, Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/User.php(1469): Domain_User->userUpdate(42879, Array)
#4 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_User->updateFields()
#5 /www/wwwroot/yunbao.com/public/appapi/index.php(15): PhalApi->response()
#6 {main}
