2021-03-16 13:53:54|ERROR|Home.GetNew|PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1'' at line 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(931): NotORM_Result->query('SELECT uid,titl...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(918): NotORM_Result->queryRows('SELECT uid,titl...', Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/Home.php(202): NotORM_Result->queryAll('SELECT uid,titl...', Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/Home.php(43): Model_Home->getNew('1')
#4 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/Home.php(460): Domain_Home->getNew('1')
#5 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_Home->getNew()
#6 /www/wwwroot/yunbao.com/public/appapi/index.php(19): PhalApi->response()
#7 {main}
2021-03-16 13:53:57|ERROR|Home.GetNew|PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1'' at line 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(931): NotORM_Result->query('SELECT uid,titl...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(918): NotORM_Result->queryRows('SELECT uid,titl...', Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/Home.php(202): NotORM_Result->queryAll('SELECT uid,titl...', Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/Home.php(43): Model_Home->getNew('1')
#4 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/Home.php(460): Domain_Home->getNew('1')
#5 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_Home->getNew()
#6 /www/wwwroot/yunbao.com/public/appapi/index.php(19): PhalApi->response()
#7 {main}
2021-03-16 13:54:05|ERROR|Home.GetNew|PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1'' at line 1 in /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php:258
Stack trace:
#0 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(931): NotORM_Result->query('SELECT uid,titl...', Array)
#1 /www/wwwroot/yunbao.com/PhalApi/PhalApi/NotORM/NotORM/Result.php(918): NotORM_Result->queryRows('SELECT uid,titl...', Array)
#2 /www/wwwroot/yunbao.com/PhalApi/Appapi/Model/Home.php(202): NotORM_Result->queryAll('SELECT uid,titl...', Array)
#3 /www/wwwroot/yunbao.com/PhalApi/Appapi/Domain/Home.php(43): Model_Home->getNew('1')
#4 /www/wwwroot/yunbao.com/PhalApi/Appapi/Api/Home.php(460): Domain_Home->getNew('1')
#5 /www/wwwroot/yunbao.com/PhalApi/PhalApi/PhalApi.php(57): Api_Home->getNew()
#6 /www/wwwroot/yunbao.com/public/appapi/index.php(19): PhalApi->response()
#7 {main}
2021-03-16 14:48:25|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///thumb/20210316/06692213051650589.png
2021-03-16 20:17:59|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///avatar/20210316/06692410799972291.png
2021-03-16 20:18:46|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///thumb/20210316/06692411262343582.png
2021-03-16 20:23:21|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///thumb/20210316/06692414018449669.png
2021-03-16 20:28:34|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///thumb/20210316/06692417146557610.png
2021-03-16 20:32:01|DEBUG|succeed to upload file to UCloud_Engine_Local|https://cdn.meppag.cn/upload///thumb/20210316/06692419212195069.png
2021-03-16 22:57:57|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"183965"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181281, '181281_16159056...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 22:58:16|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"186545"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181225, '181225_16159062...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 22:58:18|ERROR|Live.EnterRoom|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('zombie:181245:1...', '["{\\"id\\":\\"182...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1641): setcaches('zombie:181245:1...', Array, 120)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1374): Api_Live->getUserList(181245, '181245_16159050...')
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->enterRoom()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 22:59:02|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"186421"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181258, '181258_16159044...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 22:59:15|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"184533"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181236, '181236_16159062...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 22:59:27|ERROR|Live.EnterRoom|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('zombie:181229:1...', '["{\\"id\\":\\"184...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1641): setcaches('zombie:181229:1...', Array, 120)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1374): Api_Live->getUserList(181229, '181229_16159050...')
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->enterRoom()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 23:05:53|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"186323"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181261, '181261_16159032...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 23:20:58|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"181177"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181235, '181235_16159074...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 23:21:07|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('getUserLists_18...', '[{"id":"186439"...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1653): setcaches('getUserLists_18...', Array, 10)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181217, '181217_16159074...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
2021-03-16 23:21:11|ERROR|Live.GetUserLists|RedisException: read error on connection to r-j6crcpxniav4upemlfpd.redis.rds.aliyuncs.com:6379 in /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php:133
Stack trace:
#0 /www/wwwroot/admgl68.te8.tv/PhalApi/Common/functions.php(133): Redis->set('zombie:181238:1...', '["{\\"id\\":\\"181...')
#1 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1641): setcaches('zombie:181238:1...', Array, 120)
#2 /www/wwwroot/admgl68.te8.tv/PhalApi/Appapi/Api/Live.php(1601): Api_Live->getUserList(181238, '181238_16159062...', 1)
#3 /www/wwwroot/admgl68.te8.tv/PhalApi/PhalApi/PhalApi.php(57): Api_Live->getUserLists()
#4 /www/wwwroot/admgl68.te8.tv/public/appapi/index.php(19): PhalApi->response()
#5 {main}
